add IU list chunks for STH 202411a

diff --git a/sch-sth-tra/sth-scripts/generate-sth-process-commands b/sch-sth-tra/sth-scripts/generate-sth-process-commands
--- a/sch-sth-tra/sth-scripts/generate-sth-process-commands
+++ b/sch-sth-tra/sth-scripts/generate-sth-process-commands
@@ -1,23 +1,51 @@
-for disease in Tri:whipworm:trichuris ; do
-#for disease in Asc:roundworm:ascaris ; do
+#for disease in Tri:whipworm:trichuris ; do
+for disease in Asc:roundworm:ascaris ; do
 #for disease in Hook:hookworm:hookworm ; do
-    for scenario in 1 2a 2b 2c 3a 3b ; do
+	for pair in sch:europe-west3-b:aa sch2:europe-west6-b:ab sch3:europe-west6-b:ac sch4:europe-west8-b:ad epioncho:europe-west1-b:ae epioncho2:europe-west3-b:af epioncho3:europe-west4-b:ag epioncho4:europe-west2-b:ah epioncho5:europe-west4-b:ai lf-backup:europe-west1-b:aj ; do
+
+		machine=$( echo $pair | cut -f 1 -d : )
+		zone=$( echo $pair | cut -f 2 -d : )
+		chunk=$( echo $pair | cut -f 3 -d : )
 
         SHORT=$( echo $disease | cut -f 1 -d : )
         FILENAME=$( echo $disease | cut -f 2 -d : )
         SOURCENAME=$( echo $disease | cut -f 3 -d : )
 
+		RUN_IDENTIFIER="202411a-STH"
+		RUN_IU_DIRECTORY="sth-IUS-20241111"
+
         CORES=20
 
-        for chunk in aa ab ac ad ae af; do
+		IU_FILE="iu-disease-data/${RUN_IU_DIRECTORY}/${SOURCENAME}-${chunk}.csv"
 
-            echo "nohup env FORCE_ADD_TO_EXISTING_RUN=y DONT_WRITE_DB_RECORD=y bash run-sch-sth-tra.bash -d ${SHORT} -i iu-disease-data/sth-IUs-20241008-batch-4/sth-IUs-all-africa-20241008-batch-4-${FILENAME}-scenario_${scenario}-${chunk}.csv -n 200 -c ${CORES} -N 202410a-STH -e igor@artrabbit.com -s ${scenario} -p source-data-${SOURCENAME}-projections-all-africa-2025-20241008 -k ntd-disease-simulator-data -K ntd-endgame-result-data -o 202410a-STH -D -y KK2 >/dev/null </dev/null &"
+		# check file exists
+		if [[ ! -f ${IU_FILE} ]] ; then
+			echo "ERROR: IU file ${IU_FILE} not found"
+			exit 1
+		fi
+
+		# check it has header line
+		if [[ -z $( ag "Group_name" ${IU_FILE} ) ]] ; then
+			echo "-> addiing header line to ${IU_FILE}"
+			gsed -i -e '1s;^;"Group_name","IU_ID","IU_ID2"\n;' ${IU_FILE}
+		fi
+
+		echo "${machine}:${zone}"
+		echo
+		echo "gcloud compute instances start ${machine} --zone=${zone} --project=artrabbit-clients-ntd"
+		echo
+
+		for scenario in 1 2a 2b 2c 3a 3b ; do
+
+            echo "nohup env FORCE_ADD_TO_EXISTING_RUN=y DONT_WRITE_DB_RECORD=y bash run-sch-sth-tra.bash -d ${SHORT} -i iu-disease-data/${RUN_IU_DIRECTORY}/ascaris-${chunk}.csv -n 200 -c ${CORES} -N ${RUN_IDENTIFIER} -e igor@artrabbit.com -s ${scenario} -p source-data-${SOURCENAME}-projections-all-africa-2025-20241008 -k ntd-disease-simulator-data -K ntd-endgame-result-data -o ${RUN_IDENTIFIER} -D -y KK2 >/dev/null </dev/null &"
 
         done
 
         echo
+		echo "------"
+        echo
 
-    done
+	done
     echo
     echo
 done
